[package]
name = "zeroutils-ipc"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
